function UCost=UCostRebarPrefab1(ucwire,uclinks,ucrebar,quantwire,quantlinks,...
                              ucManCutBend,ucLorry,quantLorry,perfManCutBend,...
                              ucManTyeAssem,perfManTyeAssem)
    
	costWire=ucwire*quantwire;
    costLinks=uclinks*quantlinks;
    costRebar=ucrebar;
    
    costManCutBend=ucManCutBend*perfManCutBend;
    costManTyeAssem=ucManTyeAssem*perfManTyeAssem;
    costLorry=ucLorry*quantLorry;
    
    UCost=costWire+...
          costLinks+...
          costRebar+...
          costManCutBend+...
          costManTyeAssem+...
          costLorry;         
end