function [volRebar,lenRebarL,lenRebarM,lenRebarR]=volRebarDesignBeamSpan1DSec...
  (nb3l,nb3m,nb3r,abl,abm,abr,ldL3,ld3M,ld3R,nbAfterCut3L,nbAfterCut3M,...
  cutLoc,span)

%% Total length of bars (considering cuts)
[lbarL1,lbarL2,lbarL3]=lenRebarRecBeamCuts1DSec(nb3l,...
    nbAfterCut3L,span,ldL3+cutLoc(1));
[lbarM1,lbarM2,lbarM3]=lenRebarRecBeamCuts1DSec(nb3m,...
    nbAfterCut3M,span,ld3M.*2+cutLoc(3)-cutLoc(2));
[lbarR1,lbarR2,lbarR3]=lenRebarRecBeamCuts1DSec(nb3r,...
    nbAfterCut3L,0,ld3R+span-cutLoc(4));

lenRebarL=[lbarL1;lbarL2;lbarL3];
lenRebarM=[lbarM1;lbarM2;lbarM3];
lenRebarR=[lbarR1;lbarR2;lbarR3];

%% Rebar volume
volRebar=sum(lbarL1.*abl)+sum(lbarL2.*abl)+sum(lbarL3.*abl)+...
        sum(lbarM1.*abm)+sum(lbarM2.*abm)+sum(lbarM3.*abm)+...
        sum(lbarR1.*abr)+sum(lbarR2.*abr)+sum(lbarR3.*abr);
