function [volRebar,lenRebarL,lenRebarM,lenRebarR]=volRebarDesignBeamSpan...
  (nb6l,nb6m,nb6r,abl6,abm6,abr6,ldL6,ld6M,ld6R,nbAfterCut6L,nbAfterCut6M,...
  cutLoc,span)

%% Total length of bars (considering cuts)
[lbarL1,lbarL2,lbarL3,lbarL4,lbarL5,lbarL6]=lenRebarRecBeamCuts(nb6l,...
    nbAfterCut6L,span,ldL6+cutLoc(1));
[lbarM1,lbarM2,lbarM3,lbarM4,lbarM5,lbarM6]=lenRebarRecBeamCuts(nb6m,...
    nbAfterCut6M,span,ld6M.*2+cutLoc(3)-cutLoc(2));
[lbarR1,lbarR2,lbarR3,lbarR4,lbarR5,lbarR6]=lenRebarRecBeamCuts(nb6r,...
    nbAfterCut6L,0,ld6R+span-cutLoc(4));

lenRebarL=[lbarL1;lbarL2;lbarL3;lbarL4;lbarL5;lbarL6];
lenRebarM=[lbarM1;lbarM2;lbarM3;lbarM4;lbarM5;lbarM6];
lenRebarR=[lbarR1;lbarR2;lbarR3;lbarR4;lbarR5;lbarR6];

%% Rebar volume
volRebar=sum(lbarL1.*abl6(1))+sum(lbarL2.*abl6(2))+sum(lbarL3.*abl6(3))+...
        sum(lbarL4.*abl6(4))+sum(lbarL5.*abl6(5))+sum(lbarL6.*abl6(6))+...
        sum(lbarM1.*abm6(1))+sum(lbarM2.*abm6(2))+sum(lbarM3.*abm6(3))+...
        sum(lbarM4.*abm6(4))+sum(lbarM5.*abm6(5))+sum(lbarM6.*abm6(6))+...
        sum(lbarR1.*abr6(1))+sum(lbarR2.*abr6(2))+sum(lbarR3.*abr6(3))+...
        sum(lbarR4.*abr6(4))+sum(lbarR5.*abr6(5))+sum(lbarR6.*abr6(6));
