function [volRebar,lenRebarL,lenRebarM,lenRebarR]=volRebarDesignBeamSpan1DiamLayer...
  (nb3l,nb3m,nb3r,abl3,abm3,abr3,ldL3,ld3M,ld3R,nbAfterCut3L,nbAfterCut3M,...
  cutLoc,span)

%% Total length of bars (considering cuts)
[lbarL1,lbarL2,lbarL3]=lenRebarRecBeamCuts1DiamLayer(nb3l,...
    nbAfterCut3L,span,ldL3+cutLoc(1));
[lbarM1,lbarM2,lbarM3]=lenRebarRecBeamCuts1DiamLayer(nb3m,...
    nbAfterCut3M,span,ld3M.*2+cutLoc(3)-cutLoc(2));
[lbarR1,lbarR2,lbarR3]=lenRebarRecBeamCuts1DiamLayer(nb3r,...
    nbAfterCut3L,0,ld3R+span-cutLoc(4));

lenRebarL=[lbarL1;lbarL2;lbarL3];
lenRebarM=[lbarM1;lbarM2;lbarM3];
lenRebarR=[lbarR1;lbarR2;lbarR3];

%% Rebar volume
volRebar=sum(lbarL1.*abl3(1))+sum(lbarL2.*abl3(2))+sum(lbarL3.*abl3(3))+...
        sum(lbarM1.*abm3(1))+sum(lbarM2.*abm3(2))+sum(lbarM3.*abm3(3))+...
        sum(lbarR1.*abr3(1))+sum(lbarR2.*abr3(2))+sum(lbarR3.*abr3(3));
